Redesign des templates
betagouv/itou-inclusion-connect pull request #35
Opened 2023-01-31 14:28 UTC by hellodeloo

**Carte notion:** https://www.notion.so/plateforme-inclusion/Nouveau-design-pages-Inclusion-Connect-c34b0a9b7fec4e56a9a63034404caadf

**Quoi:** 
Mise a jour des templates pour correspondre a la nouvelle mise en page

2023-02-02 09:33 UTC, tonial requested changes
J'ai quelques retours de pages qui ne correspondent pas à la maquette (avec les liens).
Voici aussi un lien qui te sera utile pour naviguer dans Inclusion Connect:  https://www.notion.so/plateforme-inclusion/Doc-produit-1253040ad01f4b939d67f056e056e7d0
Tu as les différents parcours expliquez avec à chaque fois un lien pour y accéder rapidement.

2023-02-02 09:33 UTC, tonial commented on themes/inclusion-connect/login/login-reset-password.ftl
> +        <hr class="fr-mt-2w">
Il manque le `format attendu` au dessus du champ d'email
https://www.figma.com/file/PvCrXVkBAdtmY7ArEOy0Td/%F0%9F%8C%90-Landing-page---transverse-Hub-inclusion?node-id=1355%3A55378&t=wGzmr0Vd0PxKZcSe-0

Idem sur la page de création de compte : https://www.figma.com/file/PvCrXVkBAdtmY7ArEOy0Td/%F0%9F%8C%90-Landing-page---transverse-Hub-inclusion?node-id=1337%3A54799&t=v6ztbq4iDUA7KfTq-0

(je ne sais pas si c'est vraiment utile)

2023-02-02 09:33 UTC, tonial commented on themes/inclusion-connect/login/login-reset-password.ftl
> +        </ul>
On est d'accord qu'on n'arrive pas sur la page prévue dans figma (https://www.figma.com/file/PvCrXVkBAdtmY7ArEOy0Td/%F0%9F%8C%90-Landing-page---transverse-Hub-inclusion?node-id=1355%3A55568&t=wGzmr0Vd0PxKZcSe-0)

2023-02-02 09:33 UTC, tonial commented on themes/inclusion-connect/login/login-update-password.ftl
> +        <p class="fr-text--md fr-mb-3w">Entrez votre nouveau mot de passe.</p>
La page ne correspond pas à la maquette figma: https://www.figma.com/file/PvCrXVkBAdtmY7ArEOy0Td/%F0%9F%8C%90-Landing-page---transverse-Hub-inclusion?node-id=1355%3A55918&t=v6ztbq4iDUA7KfTq-0

2023-02-02 09:33 UTC, tonial commented on themes/inclusion-connect/login/info.ftl
> +            <p class="fr-text--md fr-mb-3w">${message.summary}</p>
Quand on essaye de valider son adresse email depuis un autre navigateur, on arrive sur cette page : 
![image](https://user-images.githubusercontent.com/7632730/216282670-fb20daa9-8e0a-4c03-9f05-c8b924448318.png)

Puis après avoir cliqué sur "cliquez ici" : 
![image](https://user-images.githubusercontent.com/7632730/216282880-e1984dd1-1e02-4a50-8ae9-4ade57663d3f.png)


Le bug est déjà présent cela-dit : 
![image](https://user-images.githubusercontent.com/7632730/216284093-43a5c15f-a830-4fc5-8542-3115a85f1a68.png)

J'ai l'impression que supprime le message.summary ici corrige le soucis, mais pas dit que ce soit la bonne solution.

Ça a l'air d'être un soucis de keycloak cela dit...

2023-02-03 09:14 UTC, hellodeloo commented on themes/inclusion-connect/login/login-reset-password.ftl
> +        <hr class="fr-mt-2w">
Yes, bien vu. C'est fix

2023-02-03 09:18 UTC, hellodeloo commented on themes/inclusion-connect/login/login-reset-password.ftl
> +        </ul>
Ouais ça me semble étrange ce comportement dans figma.
Je pense que le lien en bas doit bien envoyer a l'accueil de connexion, mais que potentiellement on est redirigé auto sur la page de confirmation après envoie du formulaire

2023-02-03 09:20 UTC, hellodeloo commented on themes/inclusion-connect/login/info.ftl
> +            <p class="fr-text--md fr-mb-3w">${message.summary}</p>
J'ai ajouté cette page "info" pour pouvoir custom le template mais le fonctionnement reste le même d'au début même si c'est étrange, c'était déjà comme ça

2023-02-03 10:36 UTC, merged