Draf: Mise à jour deKeycloak
betagouv/itou-inclusion-connect pull request #9
Opened 2022-08-05 09:47 UTC by tonial

Keycloak a changé de choses avec la version 17, et notamment le nom du registry docker ce qui fait que nous sommes bloqués sur la version 16.1.
Cette PR devrait permettre de passer à la nouvelle version (aujourd'hui 19.0.1), mais il faudrait pouvoir la tester correctement avant...

Point d'attention, conformément à [cette doc](https://www.keycloak.org/docs/latest/upgrading/) il faut:
- [x] Mettre à jour la base de donnée (ce qui se fait à l'aide de l'option `--spi-connections-jpa-default-migration-strategy=update`)
- [ ] Mettre à jour les templates/mesages ([voir ici](https://www.keycloak.org/docs/latest/upgrading/#migrating-templates)). Ce point nécessite d'arriver à connecter le django local d'itou sur le keycloak local...)

2022-08-09 11:56 UTC, jdauphant requested changes
Aussi, à vérifier : le secret n'est pas une copie d'un secret de prod

2022-08-09 11:56 UTC, jdauphant commented on docker/dev/keycloak/init.sh
> +    -s secret=Oigr5kt9pmdwgXaWCWSVkXyPsFwszbeC \
Bonjour @tonial
C'est mieux de ne pas mettre de secret par défaut même pour du dev/test :

sur un malentendu ça pourrait aller en prod (loi de murphy : "S'il y a plus d'une façon de faire quelque chose, et que l'une d'elles conduit à un désastre, alors il y aura quelqu'un pour le faire de cette façon")
ça déclenche les outils d'analyses de fuite (ceux qui servent à détecter la fuite de secret de production)

2 solutions alternatives :

forcer le devops à indiquer le secret dans une config (le mieux en variable d'environnement)
ou
générer le secret aléatoirement au premier lancement (dans ce cas dans la doc tu peux indiquer comment récupérer le secret)

2022-08-09 11:56 UTC, jdauphant commented on docs/development.md
> +Il faudra utiliser `client_id=local_inclusion_connect` et `client_secret=Oigr5kt9pmdwgXaWCWSVkXyPsFwszbeC`.
Idem pour le secret

2022-08-09 12:07 UTC, vperron commented on docker/dev/keycloak/init.sh
> +    -s secret=Oigr5kt9pmdwgXaWCWSVkXyPsFwszbeC \
Agreed, je pense que pour certains types de valeurs dont les secrets, URLs de services distants, etc: le lancement devrait crasher (ou indiquer a minima si on l'oublie que telle ou telle fonctionnalité sera désactivée si on veut faire du failsafe)

2022-08-09 12:19 UTC, tonial commented on docker/dev/keycloak/init.sh
> +    -s secret=Oigr5kt9pmdwgXaWCWSVkXyPsFwszbeC \
Je me posais la question justement.
Je vais donc le retirer, et mettre un echo à la fin du script pour afficher le client_secret généré par Keycloak.

2022-08-09 12:33 UTC, jdauphant approved these changes

2022-08-09 13:43 UTC, vperron approved these changes
Cool ! Quelques petits commentaires cosmétiques mais go

2022-08-09 13:43 UTC, vperron commented on Dockerfile
> +CMD ["start", "--spi-connections-jpa-default-migration-strategy", "update"]
quel est cette option ? 

et en quoi ce Dockerfile est différent de celui dans `docker/dev/keycloak` ?

2022-08-09 13:43 UTC, vperron commented on Dockerfile
> +CMD ["start", "--spi-connections-jpa-default-migration-strategy", "update"]
auquel cas peut etre mettre des commentaires, ou utiliser le dosiier `docker` dans les deux cas pour spécifier quel Dockerfile est pour la prod et lequel pour le dev. Par ailleurs, expliquer l'option complexe sera utile si un jour elle est dépréciée / inutile etc

2022-08-09 13:43 UTC, vperron commented on docs/development.md
> +NB(alaurent): Avec le dernier docker existant, j'arrive à lancer keycloak en local.
je ne suis pas certain que ce commentaire doive rester.

2022-08-09 13:43 UTC, vperron commented on docs/development.md
> +Il faudrait donc créer un script pour le faire automatiquement (utiliser un makefile plutot que docker compose ?)
super commentaire, à bien mettre en avant pour que les gens voient que c'est un work in progress.

2022-08-09 13:43 UTC, vperron commented on docs/development.md
> +Il faut ensuite se connecter à l'interface d'administration pour effectuer quelques étapes.
URL ?

2022-08-09 13:43 UTC, vperron commented on Dockerfile
> +ENV KC_FEATURES_DISABLED=impersonation
ce commit est en FIXME et dit que ça ne change rien, à retirer ?

2022-08-09 13:43 UTC, vperron commented on docker-compose.yml
> +      - 5433:5432
huhu, yes, pareil pour les conflits je suppose.

2022-08-09 13:43 UTC, vperron commented on docs/development.md
> +KeyCloak utilise une base de données PostgreSQL. Vous devez donc avoir à disposition un serveur PSQL
"est configuré dans ce repository pour utiliser une base PostgreSQL" non ?

et "vous devez avoir à disposition" est un peu piégeux car en vrai le docker-compose s'en occupe tout seul.

2022-08-09 13:43 UTC, vperron commented on docker-compose.yml
> +    image: mailhog/mailhog
<3

2022-08-09 13:43 UTC, vperron commented on docker/dev/keycloak/init.sh
> +# smtpServer.host=smtp              # Docker compose utilise le nom du dervice comme hostname
je n'aime en général pas trop les commentaires commités, mais là ça fait plaisir je pense.

2022-08-09 13:43 UTC, vperron commented on themes/inclusion-connect/email/messages/messages_fr.properties
> +emailVerificationBodyHtml=<p>Une demande de cr\u00e9ation de compte a \u00e9t\u00e9 effectu\u00e9e avec votre adresse e-mail. Si vous \u00eates \u00e0 l''origine de cette requ\u00eate, veuillez cliqu
damned y a pas moyen de gérer mieux l'encoding que ça avec les `\u00e9` froireux là ? pas grave mais pénible

2022-08-10 04:28 UTC, tonial commented on Dockerfile
> +CMD ["start", "--spi-connections-jpa-default-migration-strategy", "update"]
J'ai ajouté des commentaires pour expliquer la différence entre les deux 
- mount du theme au lieu de le copier pour une utilisation en dev plus facile
- start ou start-dev en fonction du besoin
- spi-connections-jpa-default-migration-strategy pour mettre à jour la DB.

Je pourrais bouger le dockerfile de prod, mais du coup, il faut changer la variable d'environnement CC_DOCKERFILE dans CleverCloud, donc ça rend un peu bancal le déploiement.

2022-08-10 04:28 UTC, tonial commented on docs/development.md
> +NB(alaurent): Avec le dernier docker existant, j'arrive à lancer keycloak en local.
Nope, en effet

2022-08-10 04:29 UTC, tonial commented on Dockerfile
> +ENV KC_FEATURES_DISABLED=impersonation
C'est le point en suspend pour le moment.
Il faut peut être que je creuse plus la question, ou alors l'option ne fonctionne pas en déploiement start-dev...
Je dois encore creuser en tout cas.

2022-08-10 04:32 UTC, tonial commented on docker-compose.yml
> +    image: mailhog/mailhog
C'était toi qui me l'avais conseillé il y a des années déjà :D

2022-08-10 04:33 UTC, tonial commented on docker/dev/keycloak/init.sh
> +# smtpServer.host=smtp              # Docker compose utilise le nom du dervice comme hostname
Je me suis dit que ce serait utile s'il fallait faire des modifications de savoir ce que chaque ligne fait (vu que la documentation de la CLI est perfectible...)

2022-08-10 04:33 UTC, tonial commented on themes/inclusion-connect/email/messages/messages_fr.properties
> +emailVerificationBodyHtml=<p>Une demande de cr\u00e9ation de compte a \u00e9t\u00e9 effectu\u00e9e avec votre adresse e-mail. Si vous \u00eates \u00e0 l''origine de cette requ\u00eate, veuillez cliqu
Aucune idée, je vais regarder

2022-08-10 04:35 UTC, tonial commented
Merci pour la relecture @vperron !

J'ai réorganisé les commits pour n'ajouter la documentation dev qu'à la fin et éviter toutes les modifications au fur et à mesure que j'ajoute des éléments (et j'ai retiré les NB désormais inutiles).

Je vais creuser :
- l'histoire de l'encoding
- la désactivation de l'impersonation

Et il faut voir si on souhaite bouger le Dockerfile utilisé en prod

2022-08-10 07:04 UTC, vperron commented
Je ne pense pas qu'il faille bouger le Dockerfile, mais peut etre mentionner le pourquoi de sa présence à la racine :)

2022-08-11 13:56 UTC, celine-m-s reviewed
Première passe finie. Super !!! :tada: Et bravo !
Je teste maintenant que je peux bien lancer l'environnement Docker en local.

2022-08-11 13:56 UTC, celine-m-s commented on README.md
> +## Documentation :
```suggestion
## Documentation
```

2022-08-11 13:56 UTC, celine-m-s commented on README.md
> +Vous trouverez [ici](docs/index.md) la documentation pour intégrer Inclusion Connect à votre service
Je n'aime pas trop les liens qui se cachent derrière un « ici » ou « là » car c'est trop petit et que ce n'est pas toujours évident de cliquer dessus. Mine de rien, ça ajoute une barrière mentale.
On peut remplacer par « en cliquant ici », « sur cette page » ou autre en fonction de ton imagination ! :-D

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +Les fournisseurs de service doivent donc être des clients OpenID Connect (aussi appelés relying parties). Inclusion Connect est un fournisseur OpenID Connect (aussi appelé OpenID Connect Provider).
```suggestion
Les fournisseurs de service doivent donc être des clients OpenID Connect (aussi appelés _relying parties_).  Inclusion Connect est un fournisseur OpenID Connect (aussi appelé _OpenID Connect Provider_).
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +# Utiliser Inclusion Connect pour identifier/authentifier des utilisateurs
```suggestion
# Utiliser Inclusion Connect pour authentifier des utilisateurs
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +NB: est-ce qu'on met les vrais urls ici et en dessous ?
Je dirais que non mais indiquer le format des URL est une très bonne idée. Je serais donc pour garder le tableau et ajouter une mention indiquant de nous contacter pour obtenir les variables de recette et de prod.

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +[en englais sur cette page](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint).
```suggestion
[en anglais sur cette page](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint).
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +Le thème actuel permet de personnaliser Inclusion Connect en fonction du Fournisseur de service
```suggestion
Le thème actuel permet de personnaliser Inclusion Connect en fonction du Fournisseur de service.
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +Cette personnalisation se fait à l'aide d'un paramètre `from` ajouté lors de l'appel au endpoint `Authorization`
```suggestion
Cette personnalisation se fait à l'aide d'un paramètre `from` ajouté lors de l'appel au endpoint `Authorization`.
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/openid_connect.md
> +Les valeurs gérées actuellement sont `emplois`, `dora` et `communaute` mais d'autres peuvent être ajoutée.
```suggestion
Les valeurs gérées actuellement sont `emplois`, `dora` et `communaute` mais d'autres peuvent être ajoutées.
```

2022-08-11 13:56 UTC, celine-m-s commented on Dockerfile
> +# Dockerfile for Clever Cloud deployments
```suggestion
# Dockerfile used **in a production environment** as this is the default location of a Dockerfile.
For the development one, see docker/dev/keycloak/Dockerfile
```

2022-08-11 13:56 UTC, celine-m-s commented on Dockerfile
> +# Dockerfile for Clever Cloud deployments
Je ne mentionnerais pas forcément Clever Cloud car les autres startups utilisent parfois d'autres PAAS qui fonctionnent aussi avec Docker.

2022-08-11 13:56 UTC, celine-m-s commented on docker-compose.yml
> +      - dev.env
Il faut donc un dev.env dans docker/dev/keycloak ?

2022-08-11 13:56 UTC, celine-m-s commented on docker/dev/keycloak/Dockerfile
> +ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
Note : attention au contenu qui est dupliqué.

2022-08-11 13:56 UTC, celine-m-s commented on docs/development.md
> +## Cloner le repo GitHub
```suggestion
## Cloner le dépôt GitHub
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/development.md
> +La première étape est de cloner le repo sur votre ordinateur.
```suggestion
La première étape est de cloner le dépôt sur votre ordinateur.
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/development.md
> +Cela permet de ne pas avoir besoin d'un vrai serveur SMTP et d'une vrai adresse email.
```suggestion
Cela permet de ne pas avoir besoin d'un vrai serveur SMTP et d'une vraie adresse email.
```

2022-08-11 13:56 UTC, celine-m-s commented on docs/development.md
> +Cela permet de ne pas avoir besoin d'un vrai serveur SMTP et d'une vrai adresse email.
Et c'est vrai que c'est super !!

2022-08-11 13:56 UTC, celine-m-s commented on themes/inclusion-connect/email/messages/messages_fr.properties
> +executeActionsBodyHtml=<p>Votre administrateur vient de demander une mise à jour de votre compte. Veuillez cliquer sur le lien ci-dessous afin de commencer le processus.</p><p><a href="{0}">{0}</a></
Ça fait du bien !

2022-08-11 13:56 UTC, celine-m-s commented on themes/inclusion-connect/email/messages/messages_fr.properties
> +closingHtml=<p>L''équipe d''inclusion connect</p>
EOF missing ;-)

2022-08-11 16:37 UTC, celine-m-s commented
Bon, malheureusement ça ne fonctionne pas chez moi. :crying_cat_face:
On pourra regarder ça à mon retour si tu veux.

```
cms@cms $ docker compose up
[+] Running 5/5
 ⠿ Network itou-inclusion-connect_default         Created                                                                                                                                                       0.1s
 ⠿ Volume "itou-inclusion-connect_postgres_data"  Created                                                                                                                                                       0.0s
 ⠿ Container inclusion_connect_postgres           Created                                                                                                                                                       0.1s
 ⠿ Container inclusion_connect_smtp               Created                                                                                                                                                       0.1s
 ⠿ Container inclusion_connect_keycloak           Created                                                                                                                                                       0.1s
Attaching to inclusion_connect_keycloak, inclusion_connect_postgres, inclusion_connect_smtp
inclusion_connect_smtp      | 2022/08/11 15:47:54 Using in-memory storage
inclusion_connect_smtp      | 2022/08/11 15:47:54 [SMTP] Binding to address: 0.0.0.0:1025
inclusion_connect_smtp      | [HTTP] Binding to address: 0.0.0.0:8025
inclusion_connect_smtp      | 2022/08/11 15:47:54 Serving under http://0.0.0.0:8025/
inclusion_connect_smtp      | Creating API v1 with WebPath: 
inclusion_connect_smtp      | Creating API v2 with WebPath: 
inclusion_connect_postgres  | The files belonging to this database system will be owned by user "postgres".
inclusion_connect_postgres  | This user must also own the server process.
inclusion_connect_postgres  | 
inclusion_connect_postgres  | The database cluster will be initialized with locale "en_US.utf8".
inclusion_connect_postgres  | The default database encoding has accordingly been set to "UTF8".
inclusion_connect_postgres  | The default text search configuration will be set to "english".
inclusion_connect_postgres  | 
inclusion_connect_postgres  | Data page checksums are disabled.
inclusion_connect_postgres  | 
inclusion_connect_postgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
inclusion_connect_postgres  | creating subdirectories ... ok
inclusion_connect_postgres  | selecting dynamic shared memory implementation ... posix
inclusion_connect_postgres  | selecting default max_connections ... 100
inclusion_connect_postgres  | selecting default shared_buffers ... 128MB
inclusion_connect_postgres  | selecting default time zone ... Etc/UTC
inclusion_connect_postgres  | creating configuration files ... ok
inclusion_connect_postgres  | running bootstrap script ... ok
inclusion_connect_keycloak  | Updating the configuration and installing your custom providers, if any. Please wait.
inclusion_connect_postgres  | performing post-bootstrap initialization ... ok
inclusion_connect_postgres  | syncing data to disk ... ok
inclusion_connect_postgres  | 
inclusion_connect_postgres  | 
inclusion_connect_postgres  | Success. You can now start the database server using:
inclusion_connect_postgres  | 
inclusion_connect_postgres  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
inclusion_connect_postgres  | 
inclusion_connect_postgres  | initdb: warning: enabling "trust" authentication for local connections
inclusion_connect_postgres  | You can change this by editing pg_hba.conf or using the option -A, or
inclusion_connect_postgres  | --auth-local and --auth-host, the next time you run initdb.
inclusion_connect_postgres  | waiting for server to start....2022-08-11 15:47:55.445 UTC [48] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
inclusion_connect_postgres  | 2022-08-11 15:47:55.449 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
inclusion_connect_postgres  | 2022-08-11 15:47:55.465 UTC [49] LOG:  database system was shut down at 2022-08-11 15:47:55 UTC
inclusion_connect_postgres  | 2022-08-11 15:47:55.473 UTC [48] LOG:  database system is ready to accept connections
inclusion_connect_postgres  |  done
inclusion_connect_postgres  | server started
inclusion_connect_postgres  | 
inclusion_connect_postgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgres-init.sh
inclusion_connect_postgres  | You are now connected to database "postgres" as user "postgres".
inclusion_connect_postgres  | CREATE ROLE
inclusion_connect_postgres  | CREATE DATABASE
inclusion_connect_postgres  | ALTER ROLE
inclusion_connect_postgres  | 
inclusion_connect_postgres  | waiting for server to shut down...2022-08-11 15:47:55.717 UTC [48] LOG:  received fast shutdown request
inclusion_connect_postgres  | .2022-08-11 15:47:55.721 UTC [48] LOG:  aborting any active transactions
inclusion_connect_postgres  | 2022-08-11 15:47:55.723 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
inclusion_connect_postgres  | 2022-08-11 15:47:55.723 UTC [50] LOG:  shutting down
inclusion_connect_postgres  | 2022-08-11 15:47:55.764 UTC [48] LOG:  database system is shut down
inclusion_connect_postgres  |  done
inclusion_connect_postgres  | server stopped
inclusion_connect_postgres  | 
inclusion_connect_postgres  | PostgreSQL init process complete; ready for start up.
inclusion_connect_postgres  | 
inclusion_connect_postgres  | 2022-08-11 15:47:55.845 UTC [1] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
inclusion_connect_postgres  | 2022-08-11 15:47:55.846 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
inclusion_connect_postgres  | 2022-08-11 15:47:55.846 UTC [1] LOG:  listening on IPv6 address "::", port 5432
inclusion_connect_postgres  | 2022-08-11 15:47:55.855 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
inclusion_connect_postgres  | 2022-08-11 15:47:55.866 UTC [65] LOG:  database system was shut down at 2022-08-11 15:47:55 UTC
inclusion_connect_postgres  | 2022-08-11 15:47:55.874 UTC [1] LOG:  database system is ready to accept connections
inclusion_connect_keycloak  | The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
inclusion_connect_keycloak  | 2022-08-11 15:47:55,343 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider
inclusion_connect_keycloak  | 
inclusion_connect_keycloak  | 2022-08-11 15:47:55,412 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@33abde31 to QuarkusClassLoader Augmentation Class Loader: PROD
inclusion_connect_keycloak  | 
inclusion_connect_keycloak  | 2022-08-11 15:47:55,414 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@997d532 to QuarkusClassLoader Augmentation Class Loader: PROD
inclusion_connect_keycloak  | 
inclusion_connect_keycloak  | 2022-08-11 15:47:55,415 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@273842a6 to QuarkusClassLoader Augmentation Class Loader: PROD
inclusion_connect_keycloak  | 
inclusion_connect_keycloak  | 2022-08-11 15:47:55,415 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@6a969fb8 to QuarkusClassLoader Augmentation Class Loader: PROD
inclusion_connect_keycloak  | 
inclusion_co [...]

2022-08-11 16:38 UTC, celine-m-s commented on docker/dev/postgres/psql_init.sh
> +  CREATE DATABASE $KC_DB_URL_DATABASE OWNER $KC_DB_USERNAME;
```suggestion
  CREATE DATABASE $KC_DB OWNER $KC_DB_USERNAME;
```

2022-08-11 16:38 UTC, celine-m-s commented on docker/dev/postgres/psql_init.sh
> +  CREATE DATABASE $KC_DB_URL_DATABASE OWNER $KC_DB_USERNAME;
Ça ne fonctionnait pas sinon. J'ai aussi dû changer le nom de la base de données dans dev.env (j'ai mis `ic_postgres et c'est passé).

2022-08-12 07:37 UTC, tonial commented on docker-compose.yml
> +      - dev.env
Oui, tu as raison, je vais le déplacer (mais dans ce cas, il faut mettre docker/dev/keycloak/dev.env ici

2022-08-12 07:41 UTC, tonial commented on docker/dev/keycloak/Dockerfile
> +ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
Au contenu du dockerfile ?
Oui, j'ai pas trop trouver comment faire autrement... :/

2022-08-12 07:46 UTC, tonial commented on docker/dev/postgres/psql_init.sh
> +  CREATE DATABASE $KC_DB_URL_DATABASE OWNER $KC_DB_USERNAME;
Ah, c'est une erreur en effet.
Je viens de changer le dev.env.template.

Au début j'avais voulu utiliser KC_DB_URL qui est une url au format `jdbc:postgresql://postgres/inclusion_connect`
C'est pas forcément très lisible, et en plus on avait besoin du nom de l'url dans le script et j'ai donc finalement décomposé en :
- KC_DB_URL_DATABASE=inclusion_connect
- KC_DB_URL_HOST=postgres
- KC_DB_URL_PORT=5432

Du coup la base de donnée n'arrivait pas à être initialisée, et keycloak n'arrivait pas à y accéder.

Normalement avec le nouveau dev.env.template ça devrait marcher !

2022-08-22 10:31 UTC, celine-m-s approved these changes
OK pour moi (après le déplacement de dev.env.template dans docker/dev).
Beau boulot, bravo !!

2022-08-22 12:22 UTC, merged